# Site settings
title: "Software Development | Blockchain | Data Bases"
description: "Professional Web Development, Social media marketing, Blockchain Projects and Data Base Development by itAdviser."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "itadviser.org" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "itAdviser"
user_description: "itAdviser web development Studio is an assortment of services including consultation, analytics, the creation of unique design solutions, the formation of optimal structure and content fulfilling on websites. With the experienced and competent web developers, itAdviser is more than just a web development company"
user_title: "Software Developing"
email: admin@itadviser.org
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
